### ISSUE TITLE
msifree_microservice_out plugin with iRODS 4.2

### ISSUE THREAD

**Issue by ccacciari** [EUDAT-B2SAFE/B2SAFE-core#87]
The msifree_microservice_out plugin (https://github.com/irods/contrib/issues/7#issuecomment-172605195) has not been tested yet with the iRODS version 4.2.

**Comment by cookie33** [comment]
Is it still needed with iRODS 4.2? Or are the problems fixed in the iRODS code?

**Comment by ccacciari** [comment]
Looking at the github related ticket, it seems the problem is still there, but I have not had time yet to test it. About the iRODS v4.1.x, they explicitly stated that they had not included it in the main code.
About the following versions, there is this ticket here: https://github.com/irods/irods/issues/2937, which is labeled as a milestone of the future iRODS v4.3.

**Comment by Vathasav** [comment]
I have installed Irods 4.2.1, as it is the stable version for CentOS - 7. After trying out I realised that b2safe rules that depend on msifree_microservice_out plugin are failing. Should I just switch back to  irods 4.1.x? Are there any other workarounds?

**Comment by cookie33** [comment]
There are 2 ways:
* build the msifree_microservice_out plugin
* disable the msifree_microservice_out plugin
The latter can be done by setting the parameter in `/opt/eudat/b2safe/packaging/install.conf`. This will be picked up by install.sh if you run it. Otherwise also set it to the correct value in `/opt/eudat/b2safe/rules/local.re`.
But when the plugin is disabled you might run in to memory problems..

**Comment by Vathasav** [comment]
It seems that building msifree-microservice-plugin is not a good option. I tried to build the plugin from https://github.com/irods/contrib repository. However, plugin is not working properly for the test scripts given in contributions repository. Perhaps, it is because of the development package (as already pointed by @ccacciari ) https://irods.org/download/. I am not able to find the development package for 4.2, there is only development package for 4.1.10.

**Comment by ccacciari** [comment]
Since B2SAFE has been in production for one year with iRODS v4.2.x and no out of memory issue has been reported, I close this ticket now. The lines of code related to the msifree-microservice-plugin has been removed from the rules. If needed in the future a new ticket can be opened.
